sonar.projectKey=EduTrack
sonar.projectName=EduTrack Web
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/bin/**,**/obj/**,**/Migrations/**
sonar.cs.file.suffixes=.cs
sonar.javascript.file.suffixes=.js,.jsx