// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using edutrack_academy_api.Data;

#nullable disable

namespace edutrack_academy_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121171934_BackendOverhaul")]
    partial class BackendOverhaul
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("edutrack_academy_api.Models.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Administradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Calle Principal 123",
                            FechaRegistro = new DateTime(2025, 11, 21, 17, 19, 33, 646, DateTimeKind.Utc).AddTicks(5868),
                            Telefono = "3001234567",
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoAsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoAsignaturaId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsignaturaId")
                        .HasColumnType("int");

                    b.Property<int?>("GradoId")
                        .HasColumnType("int");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("GradoId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.CursoAsignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("CursoId", "AsignaturaId")
                        .IsUnique();

                    b.ToTable("CursoAsignaturas");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acudiente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acudiente = "Carlos Pérez",
                            Apellido = "Pérez",
                            Direccion = "Calle Estudiantes 321",
                            Documento = "123456789",
                            FechaNacimiento = new DateTime(2010, 11, 21, 17, 19, 33, 646, DateTimeKind.Utc).AddTicks(5928),
                            Nivel = "10°",
                            Nombre = "Juan",
                            Telefono = "3005551234",
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Grupos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteId", "CursoId")
                        .IsUnique();

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("NotaConfigId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("NotaConfigId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.NotaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("PeriodoAcademicoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("PeriodoAcademicoId");

                    b.ToTable("NotaConfigs");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CursoAsignaturaId")
                        .HasColumnType("int");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoAsignaturaId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Observacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CursoAsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoAsignaturaId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Observaciones");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.PeriodoAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PeriodosAcademicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaFin = new DateTime(2025, 3, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Periodo 1",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = false,
                            FechaFin = new DateTime(2025, 6, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Periodo 2",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = false,
                            FechaFin = new DateTime(2025, 9, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Periodo 3",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = false,
                            FechaFin = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Periodo 4",
                            Orden = 4
                        });
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Profesores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biografia = "Docente titular de ciencias exactas",
                            Direccion = "Avenida Educación 456",
                            Especialidad = "Matemáticas",
                            FechaIngreso = new DateTime(2025, 11, 21, 17, 19, 33, 646, DateTimeKind.Utc).AddTicks(5899),
                            Telefono = "3009876543",
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("User")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Principal",
                            CreadoEn = new DateTime(2025, 11, 21, 17, 19, 33, 646, DateTimeKind.Utc).AddTicks(5661),
                            Email = "admin@edutrack.com",
                            Nombre = "Admin",
                            PasswordHash = "$2a$11$8Ax7AnCM1j7rwhhtjfiSeu41IrT9jp9.yhiAaZ1I.F7.DOPxJrj1C",
                            Rol = "admin",
                            User = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "González",
                            CreadoEn = new DateTime(2025, 11, 21, 17, 19, 33, 646, DateTimeKind.Utc).AddTicks(5672),
                            Email = "docente@edutrack.com",
                            Nombre = "María",
                            PasswordHash = "$2a$11$k26qcKoy0eZZ.!9dBbTK1ehV4VHKs3P6KyHRxY6SY3n9Pqj8VimLa",
                            Rol = "docente",
                            User = "docente"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Pérez",
                            CreadoEn = new DateTime(2025, 11, 21, 17, 19, 33, 646, DateTimeKind.Utc).AddTicks(5674),
                            Email = "estudiante@edutrack.com",
                            Nombre = "Juan",
                            PasswordHash = "$2a$11$0LjXmJvLCYOtJk9gDC11SuGeUXLEVp3G.yUpiRaY1oWXcnZ6FQxK6",
                            Rol = "estudiante",
                            User = "estudiante"
                        });
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Administrador", b =>
                {
                    b.HasOne("edutrack_academy_api.Models.Usuario", "Usuario")
                        .WithOne("AdministradorPerfil")
                        .HasForeignKey("edutrack_academy_api.Models.Administrador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Asistencia", b =>
                {
                    b.HasOne("edutrack_academy_api.Models.CursoAsignatura", "CursoAsignatura")
                        .WithMany()
                        .HasForeignKey("CursoAsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edutrack_academy_api.Models.Estudiante", "Estudiante")
                        .WithMany("Asistencias")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CursoAsignatura");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Curso", b =>
                {
                    b.HasOne("edutrack_academy_api.Models.Asignatura", null)
                        .WithMany("Cursos")
                        .HasForeignKey("AsignaturaId");

                    b.HasOne("edutrack_academy_api.Models.Grado", "Grado")
                        .WithMany("Cursos")
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("edutrack_academy_api.Models.Profesor", "Profesor")
                        .WithMany("CursosTitular")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("edutrack_academy_api.Models.Usuario", null)
                        .WithMany("CursosAsignados")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Grado");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.CursoAsignatura", b =>
                {
                    b.HasOne("edutrack_academy_api.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edutrack_academy_api.Models.Curso", "Curso")
                        .WithMany("CursoAsignaturas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edutrack_academy_api.Models.Profesor", "Profesor")
                        .WithMany("Asignaturas")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asignatura");

                    b.Navigation("Curso");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Estudiante", b =>
                {
                    b.HasOne("edutrack_academy_api.Models.Usuario", "Usuario")
                        .WithOne("EstudiantePerfil")
                        .HasForeignKey("edutrack_academy_api.Models.Estudiante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Inscripcion", b =>
                {
                    b.HasOne("edutrack_academy_api.Models.Curso", "Curso")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edutrack_academy_api.Models.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Nota", b =>
                {
                    b.HasOne("edutrack_academy_api.Models.Curso", null)
                        .WithMany("Notas")
                        .HasForeignKey("CursoId");

                    b.HasOne("edutrack_academy_api.Models.Estudiante", "Estudiante")
                        .WithMany("Notas")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edutrack_academy_api.Models.NotaConfig", "NotaConfig")
                        .WithMany()
                        .HasForeignKey("NotaConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("NotaConfig");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.NotaConfig", b =>
                {
                    b.HasOne("edutrack_academy_api.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edutrack_academy_api.Models.PeriodoAcademico", "PeriodoAcademico")
                        .WithMany("ConfiguracionesNotas")
                        .HasForeignKey("PeriodoAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("PeriodoAcademico");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Notificacion", b =>
                {
                    b.HasOne("edutrack_academy_api.Models.CursoAsignatura", "CursoAsignatura")
                        .WithMany()
                        .HasForeignKey("CursoAsignaturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("edutrack_academy_api.Models.Estudiante", "Estudiante")
                        .WithMany("Notificaciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("edutrack_academy_api.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CursoAsignatura");

                    b.Navigation("Estudiante");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Observacion", b =>
                {
                    b.HasOne("edutrack_academy_api.Models.CursoAsignatura", "CursoAsignatura")
                        .WithMany()
                        .HasForeignKey("CursoAsignaturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("edutrack_academy_api.Models.Estudiante", "Estudiante")
                        .WithMany("Observaciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edutrack_academy_api.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CursoAsignatura");

                    b.Navigation("Estudiante");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Profesor", b =>
                {
                    b.HasOne("edutrack_academy_api.Models.Usuario", "Usuario")
                        .WithOne("ProfesorPerfil")
                        .HasForeignKey("edutrack_academy_api.Models.Profesor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Asignatura", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Curso", b =>
                {
                    b.Navigation("CursoAsignaturas");

                    b.Navigation("Inscripciones");

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Estudiante", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Inscripciones");

                    b.Navigation("Notas");

                    b.Navigation("Notificaciones");

                    b.Navigation("Observaciones");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Grado", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.PeriodoAcademico", b =>
                {
                    b.Navigation("ConfiguracionesNotas");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Profesor", b =>
                {
                    b.Navigation("Asignaturas");

                    b.Navigation("CursosTitular");
                });

            modelBuilder.Entity("edutrack_academy_api.Models.Usuario", b =>
                {
                    b.Navigation("AdministradorPerfil");

                    b.Navigation("CursosAsignados");

                    b.Navigation("EstudiantePerfil");

                    b.Navigation("ProfesorPerfil");
                });
#pragma warning restore 612, 618
        }
    }
}
